config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "new", to: "games#new"
  post "score", to:"games#score"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require "open-uri"


class GamesController < ApplicationController
  def new
  alphabet = ('a'..'z').to_a
  @letters = alphabet.sample(5).join(' ')

  end
  def score
    @scoreNew = 0
    @word = params["word"]
    @letters = params["test"]

    @display = "Thats not a valid word!"
    #  includes = @letters.all? { |e| @word.include?(e) }
    url = "https://wagon-dictionary.herokuapp.com/#{@word}"
    response = URI.open(url).read
    result = JSON.parse(response)



    if result["found"] && @word.chars.all? { |e| @letters.include?(e) }
      @scoreNew += 100
    else
      @display
    end

    # if @word.include("@letters")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>  New game</h1>

<h2><%= @letters %></h2>


<p>  what is the longest word you can find?</p>
<form action="score" method="POST" data-turbo="false">
  <input type="text" name="word">
    <input type="submit" value="Ask!">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :test, @letters %>

</form>



<%= link_to 'turn back', score_path %>

app/views/games/score.html.erb
<p> Your score is <%= @scoreNew %> </p>

<%= link_to 'back', new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>